### ISSUE TITLE
Meta: Problem descriptions for waku v0

### ISSUE THREAD

**Issue by oskarth** [vacp2p/pm#2]
Meta issue to ensure we capture the issues needed for waku v0, based on Balsamiq sketch and kick off.

See project board for more details: https://github.com/orgs/vacp2p/projects/2?add_cards_query=is%3Aopen

## List

- [x]  Waku 0: Replace Whisper EIP627 with the de facto Whisper fork Status uses #27 (https://github.com/vacp2p/specs/issues/27)
- [x]  Document Waku existing light node behavior #29  (https://github.com/vacp2p/specs/issues/29)
- [x]  Waku - Ensure network compatibility between Status v1 clients (Whisper v6) and Waku 0 #14 (https://github.com/vacp2p/research/issues/14)
- [x]  Replace forked Whisper usage with Waku/0 in specs #61  (https://github.com/status-im/specs/issues/61)

- [x]  Waku 0: peers discovery mechanism #32  (https://github.com/vacp2p/specs/issues/32)
- [x]  Waku 0: message confirmation #30 (https://github.com/vacp2p/specs/issues/30)

- [x] @adamb https://github.com/orgs/vacp2p/projects/2#card-29347738
- [x] @kdeme https://github.com/orgs/vacp2p/projects/2#card-29347763
- [x] @kdeme https://github.com/orgs/vacp2p/projects/2#card-29347736
- [x] @decanus https://github.com/orgs/vacp2p/projects/2#card-29346745
- [x] @decanus / (@oskarth ) https://github.com/orgs/vacp2p/projects/2#card-29347390
- [x] @cammellos https://github.com/orgs/vacp2p/projects/2#card-29347076
- [ ] @adamb https://github.com/orgs/vacp2p/projects/2#card-29347709
- [x] (Jakub / ? https://github.com/orgs/vacp2p/projects/2#card-29347687)
- [x] (Corey / ? https://github.com/orgs/vacp2p/projects/2#card-29347360)

**Comment by oskarth** [comment]
Ping on creating these issues:

- status/spec: current v1 spec clearly marked as such - ? @corpetty
- Rate limit: Packet code feedback for rate limiting [needs more detail] - @adambabik
- vac/specs: fork out subtasks of waku 0 optionals - @decanus
- [repo?] cross-client testing: issue for cross-client testing and what we hope to gain from it vs theoretical model and empirical usage - @adambabik

Please replace empty cards in scratch in project board with the created issues and post ack here.

@jakubgs For issue re deploying waku/0 nodes, I can open this. Where do you want it?

**Comment by oskarth** [comment]
> vac/specs: fork out subtasks of waku 0 optionals - Dean? (Oskar)

@decanus I created all the other subtasks, see https://github.com/vacp2p/specs/issues/27 and project board

**Comment by oskarth** [comment]
Corey's spec issue is here: https://github.com/vacp2p/pm/issues/4 and I created the cluster one here: https://github.com/status-im/specs/issues/65

Ping @adambabik when you are done please put issues in Waku project board and close this issue.

**Comment by adambabik** [comment]
@oskarth added issues to card but I can't assign an issues across organisations and I can't edit this issue.

**Comment by oskarth** [comment]
Thanks!

> I can't assign an issues across organisations
Hack: drop link to issue in new issue from project view

> and I can't edit this issue.
Hm, weird. Some permission thing? Not sure what tho :/

**Comment by oskarth** [comment]
Added.

> > [repo?] cross-client testing: issue for cross-client testing and what we hope to gain from it vs theoretical model and empirical usage - Adam?

This one?

**Comment by adambabik** [comment]
@oskarth let's keep this one as a card because it will affect Nim and Go implementation. I need to think about how it could look like. cc @kdeme as I will need your help.
