### ISSUE TITLE
Waku client spec checklist

### ISSUE THREAD

**Issue by oskarth** [vacp2p/pm#7]
As of February 12, Waku spec 0.3 (see https://specs.vac.dev/waku/waku.html) (This doesn't cover Waku mailserver spec or Waku data field spec). Note that there MAY be aspects that are not captured explicit in this list. If these are brought to our attention, they SHOULD be amended either in issue or PR in specs repo.

## MUST and MUST NOT
- [ ] 1. For nodes to communicate, they MUST implement devp2p and run RLPx.
- [ ] 2. They MUST have some way of connecting to other nodes.
- [ ] 3. A node MUST NOT send expired envelopes, unless the envelopes are sent as a [mailserver](./mailserver.md) response.
- [ ] 4. These packets MUST be RLP-encoded arrays of data containing two objects: packet code followed by another object
- [ ] 5. Messages with unknown codes MUST be ignored without generating any error, for forward compatibility of future versions.
- [ ] 6. The Waku sub-protocol MUST support the following packet codes: [see spec]
- [ ] 7. The Status message serves as a Waku handshake and peers MUST exchange this message upon connection.
- [ ] 8. It MUST be sent after the RLPx handshake and prior to
- [ ] 9. A Waku node MUST await the Status message from a peer before engaging in other Waku protocol activity with that peer.
- [ ] 10. [...] the node MUST ignore these messages and SHOULD disconnect from that peer.
- [ ] 11. Status messages received after the handshake is completed MUST also be ignored.
- [ ] 12. The status message MUST contain an association list containing various options.
- [ ] 13. [...] ordering of the key-value pairs is not guaranteed and therefore MUST NOT be relied on.
- [ ] 14. [...] Peers MUST only send envelopes with specified topics.
- [ ] 15. Light nodes MUST NOT forward any incoming messages, they MUST only send their own messages.
- [ ] 16. The node with the higher version will decide if compatibility can be assured between versions, if this is not the case it MUST disconnect.

## SHOULD and SHOULD NOT
- [ ] 17. A node SHOULD relay messages to all connected nodes if an envelope matches their PoW and bloom filter settings.
- [ ] 18. A node SHOULD NOT send a message to a peer that it has already sent before.
- [ ] 19. When a node does not receive the Status message from a peer, before a configurable timeout, it SHOULD disconnect from that peer.
- [ ] 20. Upon retrieval of the Status message, the node SHOULD validate the message
- [ ] 21. [...] message is received, the node MUST ignore these messages and SHOULD disconnect from that peer.
- [ ] 22. In order to provide basic Denial-of-Service attack protection, each node SHOULD define its own rate limits.
- [ ] 23. The rate limits SHOULD be applied on IPs, peer IDs, and envelope topics.
- [ ] 24. Each node SHOULD broadcast its rate limits to its peers using the rate limits packet.
- [ ] 25. Each node SHOULD respect rate limits advertised by its peers.
- [ ] 26. The number of packets SHOULD be throttled in order not to exceed peer's rate limits.
- [ ] 27. When light nodes happen to connect to each other, they SHOULD disconnect. As this would result in messages being dropped between the two.
- [ ] 28. Every epoch (say, every minute or every time an event happens) statistics SHOULD be aggregated and saved by the client:
- [ ] 29. The way this SHOULD be accomplished in the future is by negotiating the versions of subprotocols [./.]
- [ ] 30. [...] the node with a lower number SHOULD assume backwards compatiblity.
- [ ] 31. Resource restricted devices SHOULD use [EIP-1459](https://eips.ethereum.org/EIPS/eip-1459) to discover nodes.

## MAY
- [ ] 32. If a node works in light mode, it MAY choose not to forward envelopes.
- [ ] 33. Each node MAY decide to whitelist, i.e. do not rate limit, selected IPs or peer IDs.
- [ ] 34. If a peer exceeds node's rate limits, the connection between them MAY be dropped.
- [ ] 35. The rate limits MAY also be sent as an optional parameter in the handshake.
- [ ] 36. If the limit gets exceeded, the connection MAY be dropped by the peer.
- [ ] 37. A node MAY send a message confirmation for any batch of messages received with a packet Messages Code.
- [ ] 38. Nodes MAY implement accounting, keeping track of resource usage.
- [ ] 39. Known static nodes MAY also be used.

**How it was produced**

`> grep SHOULD waku/waku.md `, etc, then split into one liners.

## How to use

@adambabik @kdeme 

1. Please reply here with a copy of the list and check all the things that are supported.
2. If it needs more detail, please add that to the issue. For example optional packet codes can be supported to various degrees.
3. This means we can talk about clients in precise language, e.g. "the Nimbus client supports waku 0.3 spec, with the following capabilities: [...], it doesn't implement [...]".
4. This should be captured clearly in the client repo, so anyone can see what spec it is supporting and with what modifications.
5. This client spec state repo may be abbreviated, the list above is purely to make sure all things are covered

## Acceptance criteria

1. We have 100% clarity on what each client supports and doesn't
2. Each client has a canonical home, e.g. a markdown file, where it states which spec it supports and in what state

## Notes
We can also use this for https://github.com/vacp2p/specs/issues/101

Going forward, this should only be needed for each spec version diff. We are doing this now because there's a lack of clarity about what each client supports, and this hasn't been solved yet.

cc @decanus also if there are things missing from the above checklist that should be captured.

**Comment by kdeme** [comment]
As of https://github.com/status-im/nimbus/commit/0a6e1b4ba7b8eac8cd5e287808cabf74fedf0460

## MUST and MUST NOT
- [x] 1. For nodes to communicate, they MUST implement devp2p and run RLPx.
- [x] 2. They MUST have some way of connecting to other nodes.
- [x] 3. A node MUST NOT send expired envelopes, unless the envelopes are sent as a [mailserver](./mailserver.md) response.
- [x] 4. These packets MUST be RLP-encoded arrays of data containing two objects: packet code followed by another object
- [x] 5. Messages with unknown codes MUST be ignored without generating any error, for forward compatibility of future versions.
- [x] 6. The Waku sub-protocol MUST support the following packet codes: [see spec]
- [x] 7. The Status message serves as a Waku handshake and peers MUST exchange this message upon connection.
- [x] 8. It MUST be sent after the RLPx handshake and prior to
- [x] 9. A Waku node MUST await the Status message from a peer before engaging in other Waku protocol activity with that peer.
- [x] 10. [...] the node MUST ignore these messages and SHOULD disconnect from that peer.
- [x] 11. Status messages received after the handshake is completed MUST also be ignored.
- [x] 12. The status message MUST contain an association list containing various options.
- [x] 13. [...] ordering of the key-value pairs is not guaranteed and therefore MUST NOT be relied on.
- [x] 14. [...] Peers MUST only send envelopes with specified topics.
- [x] 15. Light nodes MUST NOT forward any incoming messages, they MUST only send their own messages.
- [ ] 16. The node with the higher version will decide if compatibility can be assured between versions, if this is not the case it MUST disconnect. **NOTE: As there is currently only 1 version (waku/0), the Node decides to disconnect if it is not equal, so this is not fully compliant. To fix.**

## SHOULD and SHOULD NOT
- [x] 17. A node SHOULD relay messages to all connected nodes if an envelope matches their PoW and bloom filter settings.
- [x] 18. A node SHOULD NOT send a message to a peer that it has already sent before.
- [x] 19. When a node does not receive the Status message from a peer, before a configurable timeout, it SHOULD disconnect from that peer. **NOTE: timeout set at 5 seconds**
- [x] 20. Upon retrieval of the Status message, the node SHOULD validate the message
- [] 21. [...] message is received, the node MUST ignore these messages and SHOULD disconnect from that peer. **NOTE: no disconnect done here at the moment**
- [ ] 22. In order to provide basic Denial-of-Service attack protection, each node SHOULD define its own rate limits. **NOTE: no rate limits implemented, no rate limits passed**
- [ ] 23. The rate limits SHOULD be applied on IPs, peer IDs, and envelope topics.
- [ ] 24. Each node SHOULD broadcast its rate limits to its peers using the rate limits packet.
- [ ] 25. Each node SHOULD respect rate limits advertised by its peers.
- [ ] 26. The number of packets SHOULD be throttled in order not to exceed peer's rate limits.
- [x] 27. When light nodes happen to connect to each other, they SHOULD disconnect. As this would result in messages being dropped between the two.
- [x] 28. Every epoch (say, every minute or every time an event happens) statistics SHOULD be aggregated and saved by the client: **NOTE: Metrics on envelope statistics are gathered**
- [ ] 29. The way this SHOULD be accomplished in the future is by negotiating the versions of subprotocols [./.]
- [ ] 30. [...] the node with a lower number SHOULD assume backwards compatiblity.
- [ ] 31. Resource restricted devices SHOULD use [EIP-1459](https://eips.ethereum.org/EIPS/eip-1459) to discover nodes.

## MAY
- [x] 32. If a node works in light mode, it MAY choose not to forward envelopes.
- [ ] 33. Each node MAY decide to whitelist, i.e. do not rate limit, selected IPs or peer IDs.
- [ ] 34. If a peer exceeds node's rate limits, the connection between them MAY be dropped.
- [x] 35. The rate limits MAY also be sent as an optional parameter in the handshake.
- [ ] 36. If the limit gets exceeded, the connection MAY be dropped by the peer.
- [ ] 37. A node MAY send a message confirmation for any batch of messages received with a packet Messages Code.
- [ ] 38. Nodes MAY implement accounting, keeping track of resource usage.
- [x] 39. Known static nodes MAY also be used.

**Comment by adambabik** [comment]
https://github.com/status-im/status-go/commit/1b515a5a5e39de28793e5e0dd873632ae0416d37

## MUST and MUST NOT
- [x] 1. For nodes to communicate, they MUST implement devp2p and run RLPx.
- [x] 2. They MUST have some way of connecting to other nodes.
- [x] 3. A node MUST NOT send expired envelopes, unless the envelopes are sent as a [mailserver](./mailserver.md) response.
- [x] 4. These packets MUST be RLP-encoded arrays of data containing two objects: packet code followed by another object
- [x] 5. Messages with unknown codes MUST be ignored without generating any error, for forward compatibility of future versions.
- [ ] 6. The Waku sub-protocol MUST support the following packet codes: [see spec]
- [x] 7. The Status message serves as a Waku handshake and peers MUST exchange this message upon connection.
- [x] 8. It MUST be sent after the RLPx handshake and prior to
- [x] 9. A Waku node MUST await the Status message from a peer before engaging in other Waku protocol activity with that peer.
- [x] 10. [...] the node MUST ignore these messages and SHOULD disconnect from that peer.
- [x] 11. Status messages received after the handshake is completed MUST also be ignored.
- [x] 12. The status message MUST contain an association list containing various options.
- [x] 13. [...] ordering of the key-value pairs is not guaranteed and therefore MUST NOT be relied on.
- [x] 14. [...] Peers MUST only send envelopes with specified topics.
- [x] 15. Light nodes MUST NOT forward any incoming messages, they MUST only send their own messages.
- [ ] 16. The node with the higher version will decide if compatibility can be assured between versions, if this is not the case it MUST disconnect.

## SHOULD and SHOULD NOT
- [x] 17. A node SHOULD relay messages to all connected nodes if an envelope matches their PoW and bloom filter settings.
- [x] 18. A node SHOULD NOT send a message to a peer that it has already sent before.
- [ ] 19. When a node does not receive the Status message from a peer, before a configurable timeout, it SHOULD disconnect from that peer.
- [x] 20. Upon retrieval of the Status message, the node SHOULD validate the message
- [ ] 21. [...] message is received, the node MUST ignore these messages and SHOULD disconnect from that peer.
- [x] 22. In order to provide basic Denial-of-Service attack protection, each node SHOULD define its own rate limits.
- [ ] 23. The rate limits SHOULD be applied on IPs, peer IDs, and envelope topics.
- [ ] 24. Each node SHOULD broadcast its rate limits to its peers using the rate limits packet.
- [ ] 25. Each node SHOULD respect rate limits advertised by its peers.
- [ ] 26. The number of packets SHOULD be throttled in order not to exceed peer's rate limits.
- [x] 27. When light nodes happen to connect to each other, they SHOULD disconnect. As this would result in messages being dropped between the two.
- [ ] 28. Every epoch (say, every minute or every time an event happens) statistics SHOULD be aggregated and saved by the client:
- [ ] 29. The way this SHOULD be accomplished in the future is by negotiating the versions of subprotocols [./.]
- [ ] 30. [...] the node with a lower number SHOULD assume backwards compatiblity.
- [ ] 31. Resource restricted devices SHOULD use [EIP-1459](https://eips.ethereum.org/EIPS/eip-1459) to discover nodes.

## MAY
- [x] 32. If a node works in light mode, it MAY choose not to forward envelopes.
- [x] 33. Each node MAY decide to whitelist, i.e. do not rate limit, selected IPs or peer IDs.
- [ ] 34. If a peer exceeds node's rate limits, the connection between them MAY be dropped.
- [x] 35. The rate limits MAY also be sent as an optional parameter in the handshake.
- [ ] 36. If the limit gets exceeded, the connection MAY be dropped by the peer.
- [x] 37. A node MAY send a message confirmation for any batch of messages received with a packet Messages Code.
- [x] 38. Nodes MAY implement accounting, keeping track of resource usage.
- [x] 39. Known static nodes MAY also be used.

--- 

The missing parts:
- Exchange topic-interest (`21`) is in progress.
- Protocol Version negotiation; currently the version check is strict.
- Implement broadcasting rate limit settings.
- Enforce rate limits,
- EIP-1459.

**Comment by oskarth** [comment]
Thanks both! How do you think we should best summarize and ensure this data is kept up to date? Also cc @decanus and @cammellos 

IMO we'd want something like:
1. **Clients** Each client has a markdown file where it states the specific choices it makes and what it supports/doesn't support. This can be in a summarized form (e.g.: doesn't support rate limiting)
2. **Status spec** Status spec should make it clear what additional choices it makes when it comes to using the protocol in terms of at the interface level, so this would be things like 'using waku v0.3, with rate limits and mailservers etc'. At this level multiple clients can be used
3. **Waku spec** A brief summary of the various client implementations in terms of capabilities. Not sure how granular we want this, probably pretty high level but something similar to EIP support. E.g. "status-nim and status-go are compliant with spec v0.3 but not v.1, rate limit / mailserver support doesn't exist for this client. This can also be an appendix, and should essentially be a mirror of 1 above, albeit in a uniform format (e.g. clients might have a roadmap, but this is irrelevant for the spec).

>  6. The Waku sub-protocol MUST support the following packet codes: [see spec]

@adambabik Which of the required packet codes does the status-go client not support? Is this the Status WIP one? Is there a PR for it?

**Comment by oskarth** [comment]
Took a stab at it.

# Nimbus

`waku.md`

*Last updated February 14, 2020*

status-nim client of Waku is spec compliant with [Waku spec v0.3](https://specs.vac.dev/waku.html) with the exception of:
- Currently nodes with higher version don't automatically disconnect if versions are different

It doesn't yet implement the following recommended features:
- No support for rate limiting
- No support for DNS discovery to find Waku nodes
- It doesn't disconnect a peer if it receives a message before a Status message
- No support for negotiation with peer supporting multiple version

Additionally it makes the following choices:
- It doesn't send message confirmations
- It has partial support for accounting

# status-go

`waku.md`

*Last updated February 14, 2020*

status-nim client of Waku is spec compliant with [Waku spec v0.3](https://specs.vac.dev/waku.html) with the exception of:
- It doesn't support all the MUST packet codes (!)
- Currently nodes with higher version don't automatically disconnect if versions are different

It doesn't yet implement the following recommended features:
- It doesn't disconnect a peer if it receives a message before a Status message
- Partial support for rate limiting
- No support for DNS discovery to find Waku nodes
- No support for negotiation with peer supporting multiple version
- Exchange topic-interest packet code isn't implemented yet (WIP status-im/status-go#1853)

Additionally it makes the following choices:
- It doesn't enforce rate limit policy

# Status spec

TBD.

# Waku spec

`waku.md`

| Client     | Spec supported | Details                   |
----------------------------------------------------------|
| Nimbus     | v0.3*          | [link](nimbus/waku.md)    |
| status-go  | v0.3*          | [link](status-go/waku.md) |

* Fully compliant, except *Currently nodes with higher version don't automatically disconnect if versions are different*. For more details, see client notes.*

---

# Notes

For each client, each item can have a link to an issue and possibly rationale. If there's disagreement on a feature being necessary, let's fix it upstream! E.g. turn a SHOULD into a MAY, etc.

I'm not sure how much we want to elaborate on capabilities in Waku spec. Assuming we factor these out appropriately, this support should be evident from each sub spec (mailserver, data field, rate limiting, routing, accounting, etc). Open to ideas here.

**Comment by adambabik** [comment]
> Which of the required packet codes does the status-go client not support? Is this the Status WIP one? Is there a PR for it?

Packet `21` which is going to be obsolete together with others. They all will be replaced with a single packet which will take `status-options` alist, the same used in the handshake. @cammellos is working on it.

> Currently nodes with higher version don't automatically disconnect if versions are different

They actually do this. If versions are different they disconnect. But looking at the spec, they might choose not to if they are compatible.

> It doesn't disconnect a peer if it receives a message before a Status message

This is not true. It won't accept any other messages before Status message. If the first message is different than Status message, peers will disconnect. But it's not time limited. In theory, they can connect and wait for the Status message forever.

**Comment by oskarth** [comment]
@adambabik I based it on my reading of your checkmarks, maybe I misunderstood it. Please add to the the PR as appropriate https://github.com/status-im/status-go/pull/1855 - I only started to make it to make sure it was captured as soon as possible.

**Comment by oskarth** [comment]
Addressed. Let's make sure we keep this up to date with new versions https://specs.vac.dev/specs/waku/waku.html#appendix-b-implementation-notes
